baseURL = 'https://ganlanc.at'
title = "Ganlancat Ameyama's Blog"
theme = 'brewm'
enableRobotsTXT = true
[services.rss]
    limit = -1
[params]
    title = "Ganlancat Ameyama's Blog"
    description = "An neko."
    copyright = "CC BY-SA 4.0 International"
    [params.author]
        name = 'Ganlancat Ameyama'
        email = 'amcjedhfeh@gmail.com'
    [params.home]
        disableSlide = false
        disableListing = true
    [params.posts]
        noIndent = true
        sfdefault = true
